### ISSUE TITLE
ISSUE: -params = {'start': } not set to 25

### ISSUE THREAD

**Issue by prokopyev** [mandeep/Job-Automate#2]
Hi Mandeep, 

Testing the script reveals that -params = {'start': 0} does not change to -params = {'start': 25} after user types "yes" to contunue search beyond intial 25 results.

Best,
Anton

**Comment by mandeep** [comment]
Hi Anton, 

Thanks for letting me know about this. Unfortunately, my Indeed Publisher ID is not currently working so I'm unable to test this on my side. Could you let me know what happens after you type 'yes' into the command line?

Thanks,
Mandeep

**Comment by mandeep** [comment]
The issue arose when separating the API request and parameters invocation. The latest patch seems to have fixed this issue. Thanks for reporting this and please let me know if you have any additional problems!
